version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    image: spacedebris/node-docker-sandbox
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.15
  redis:
    image: redis
volumes:
  mongo-db: