version: '3'
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=spacedebris
      - MONGO_PASSWORD=spacedebris
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spacedebris
      - MONGO_INITDB_ROOT_PASSWORD=spacedebris

